***1. Import Pandas***

In [2]:
import pandas as pd

***2. Opening a local csv file***

In [4]:
df = pd.read_csv("/content/anime.csv")
df

    Rank                                              Title  Score
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71

***3. Opening a csv file from URL***

In [5]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

***4. Sap Parameter***

By defalt read_csv as sep paremeter is sep=',' but in .tsv file is seperated with '\t' means tab[link text](https://)

In [7]:
df = pd.read_csv("/content/file.tsv", sep='\t',names=['NO','Rollno.','number','contect'])
df

         NO  Rollno.  number    contect
0         0       50       5  881250949
1         0      172       5  881250949
2         0      133       1  881250949
3       196      242       3  881250949
4       186      302       3  891717742
...     ...      ...     ...        ...
99998   880      476       3  880175444
99999   716      204       5  879795543
100000  276     1090       1  874795795
100001   13      225       2  882399156
100002   12      203       3  879959583

[100003 rows x 4 columns]

***Index_col parameter***

Aisa index jo analysis me kaam n aaye to use aap chaho to index me badal sakte hai

In [8]:
pd.read_csv("/content/anime.csv", index_col="Rank")

                                                  Title  Score
Rank
1     Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
2     Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
3     Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
4     Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
5     Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05
6     Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04
7     Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04
8     Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04
9     Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04
10    Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03
11    Shingeki no Kyojin: The Final Season - Kankets...   9.03
12    Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02
13    Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99
14    Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99
15    Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98
16    GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94
17    Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94
18    3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93
19    Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93
20    Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91
21    Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91
22    Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89
23    Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88
24    Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88
25    MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87
26    Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84
27    Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84
28    Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83
29    The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83
30    Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82
31    Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82
32    Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81
33    Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81
34    Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80
35    Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80
36    Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79
37    Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79
38    "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79
39    Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78
40    Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78
41    Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77
42    Shingeki no Kyojin: The Final Season Part 2TV ...   8.77
43    Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76
44    Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75
45    Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75
46    Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74
47    Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73
48    Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72
49    Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71
50    Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71

***Header Parameter***

tell the parameter which row contain the column name

In [9]:
url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
df = pd.read_csv(url,header = 1)
df

       Algeria         AFRICA
0       Angola         AFRICA
1        Benin         AFRICA
2     Botswana         AFRICA
3      Burkina         AFRICA
4      Burundi         AFRICA
..         ...            ...
188   Paraguay  SOUTH AMERICA
189       Peru  SOUTH AMERICA
190   Suriname  SOUTH AMERICA
191    Uruguay  SOUTH AMERICA
192  Venezuela  SOUTH AMERICA

[193 rows x 2 columns]

***use_cols parameter ***

data import karte time he hame jo col chaheye vo data ko bata sakte hai aur baki automatically hat jaeyega

In [10]:
pd.read_csv("/content/aug_train-selected-columns.csv", usecols=['enrollee_id', 'city', 'gender','education_level' ])

     enrollee_id  city  gender  education_level
0            NaN   NaN     NaN              NaN
1            NaN   NaN     NaN              NaN
2            NaN   NaN     NaN              NaN
3            NaN   NaN     NaN              NaN
4            NaN   NaN     NaN              NaN
..           ...   ...     ...              ...
119          NaN   NaN     NaN              NaN
120          NaN   NaN     NaN              NaN
121          NaN   NaN     NaN              NaN
122          NaN   NaN     NaN              NaN
123          NaN   NaN     NaN              NaN

[124 rows x 4 columns]

***Encoding parameter ***

The encoding parameter in pandas.read_csv() tells Pandas how the text in the file is encoded

In [15]:
pd.read_csv("/content/reviews.csv", encoding='latin-1')

,Index,Name,Overall_Rating,Cuisine,Rate for two,City,Review
0,0,Oliver Brown,3.9,"Cafe, Coffee, Shake, Juices, Beverages, Waffle...",500,ahmedabad,Been to this place 3-4 times. Prakash is alway...
1,1,Oliver Brown,3.9,"Cafe, Coffee, Shake, Juices, Beverages, Waffle...",500,ahmedabad,I recently visited Oliver Brown on a weekend f...
2,2,Crush Coffee,3,"Cafe, Shake, Beverages, Desserts",600,ahmedabad,Very watery ans thin shake
3,3,The Mohalla,3.8,Cafe,550,ahmedabad,it was not cheese burst pizza.. only cheeze wa...
4,4,The Mohalla,3.8,Cafe,550,ahmedabad,"Yammi.,....test burger is best I love 💗 this B..."
...,...,...,...,...,...,...,...
770,770,The Food Garden,-,"Cafe, Salad, Healthy Food, Fast Food, North In...",850,chandigarh,The taste is good but the quantity is low as c...
771,771,The Food Garden,-,"Cafe, Salad, Healthy Food, Fast Food, North In...",850,chandigarh,pathetic food rejected
772,772,The Food Garden,-,"Cafe, Salad, Healthy Food, Fast Food, North In...",850,chandigarh,"thupka pack on cold drink packing, taste less,..."
773,773,The Food Garden,-,"Cafe, Salad, Healthy Food, Fast Food, North In...",850,chandigarh,very fast dilver
774,774,The Food Garden,-,"Cafe, Salad, Healthy Food, Fast Food, North In...",850,chandigarh,Tried their Hummus and Pita bread today. Didn'...