In [30]:
import pandas as pd
import numpy as np

In [31]:
date = pd.read_csv("orders.csv")
time = pd.read_csv("messages.csv")

In [32]:
date.head(5)

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [33]:
date.info()
# by this we know that data is onject so we have not perform operaction on it

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [34]:
time.info()
# here also

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# working with Date

In [35]:
#Converting to datatype
date['date'] = pd.to_datetime(date['date'])

In [36]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

# Extract Year

In [37]:
date['date_year'] = date['date'].dt.year
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

# Extract months

In [38]:
date['date_month'] = date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10
3 2019-08-17        7292       25       1       2019           8
4 2019-01-06        4344       25       3       2019           1

In [39]:
date['date_month'] = date['date'].dt.month_name()
date.head()

        date  product_id  city_id  orders  date_year date_month
0 2019-12-10        5628       25       3       2019   December
1 2018-08-15        3646       14     157       2018     August
2 2018-10-23        1859       25       1       2018    October
3 2019-08-17        7292       25       1       2019     August
4 2019-01-06        4344       25       3       2019    January

# Extract day

In [40]:
date["date_day"] = date['date'].dt.day
date.head()

        date  product_id  city_id  orders  date_year date_month  date_day
0 2019-12-10        5628       25       3       2019   December        10
1 2018-08-15        3646       14     157       2018     August        15
2 2018-10-23        1859       25       1       2018    October        23
3 2019-08-17        7292       25       1       2019     August        17
4 2019-01-06        4344       25       3       2019    January         6

# Extract day of week

In [41]:
date['date_ofweek'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,date_ofweek
0,2019-12-10,5628,25,3,2019,December,10,1
1,2018-08-15,3646,14,157,2018,August,15,2
2,2018-10-23,1859,25,1,2018,October,23,1
3,2019-08-17,7292,25,1,2019,August,17,5
4,2019-01-06,4344,25,3,2019,January,6,6

In [42]:
# day of week _name
date['date_dow_name'] = date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,date_ofweek,date_dow_name
0,2019-12-10,5628,25,3,2019,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,August,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,October,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,August,17,5,Saturday
4,2019-01-06,4344,25,3,2019,January,6,6,Sunday

In [43]:
date.drop(columns=['product_id', 'city_id', 'orders'], inplace=True)

date.head()

        date  date_year date_month  date_day  date_ofweek date_dow_name
0 2019-12-10       2019   December        10            1       Tuesday
1 2018-08-15       2018     August        15            2     Wednesday
2 2018-10-23       2018    October        23            1       Tuesday
3 2019-08-17       2019     August        17            5      Saturday
4 2019-01-06       2019    January         6            6        Sunday

# is weekend?

In [44]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday','Saturday']),0,1)
date.head()

,date,date_year,date_month,date_day,date_ofweek,date_dow_name,date_is_weekend
0,2019-12-10,2019,December,10,1,Tuesday,1
1,2018-08-15,2018,August,15,2,Wednesday,1
2,2018-10-23,2018,October,23,1,Tuesday,1
3,2019-08-17,2019,August,17,5,Saturday,0
4,2019-01-06,2019,January,6,6,Sunday,0

In [49]:
# extract week of year
date['date_week'] = date['date'].dt.isocalendar().week
date.head()

,date,date_year,date_month,date_day,date_ofweek,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,December,10,1,Tuesday,1,50
1,2018-08-15,2018,August,15,2,Wednesday,1,33
2,2018-10-23,2018,October,23,1,Tuesday,1,43
3,2019-08-17,2019,August,17,5,Saturday,0,33
4,2019-01-06,2019,January,6,6,Sunday,0,1

In [51]:
# extract quarter

date['Quarter']=date['date'].dt.quarter
date.head()

,date,date_year,date_month,date_day,date_ofweek,date_dow_name,date_is_weekend,date_week,Quarter
0,2019-12-10,2019,December,10,1,Tuesday,1,50,4
1,2018-08-15,2018,August,15,2,Wednesday,1,33,3
2,2018-10-23,2018,October,23,1,Tuesday,1,43,4
3,2019-08-17,2019,August,17,5,Saturday,0,33,3
4,2019-01-06,2019,January,6,6,Sunday,0,1,1

In [52]:
# extract semester
date['semester'] = np.where(date['Quarter'].isin([1,2]),1,2)
date.head()

,date,date_year,date_month,date_day,date_ofweek,date_dow_name,date_is_weekend,date_week,Quarter,semester
0,2019-12-10,2019,December,10,1,Tuesday,1,50,4,2
1,2018-08-15,2018,August,15,2,Wednesday,1,33,3,2
2,2018-10-23,2018,October,23,1,Tuesday,1,43,4,2
3,2019-08-17,2019,August,17,5,Saturday,0,33,3,2
4,2019-01-06,2019,January,6,6,Sunday,0,1,1,1

In [53]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 9, 22, 12, 48, 4, 836722)

In [54]:
today-date['date']

0     2478 days 12:48:04.836722
1     2960 days 12:48:04.836722
2     2891 days 12:48:04.836722
3     2593 days 12:48:04.836722
4     2816 days 12:48:04.836722
                 ...
995   2906 days 12:48:04.836722
996   2847 days 12:48:04.836722
997   2695 days 12:48:04.836722
998   2760 days 12:48:04.836722
999   2534 days 12:48:04.836722
Name: date, Length: 1000, dtype: timedelta64[ns]

In [55]:
# if you only need days
(today-date['date']).dt.days

0      2478
1      2960
2      2891
3      2593
4      2816
       ...
995    2906
996    2847
997    2695
998    2760
999    2534
Name: date, Length: 1000, dtype: int64

In [58]:
# month passed
np.round((today - date['date']).dt.days / 30, 0)

0      83.0
1      99.0
2      96.0
3      86.0
4      94.0
       ...
995    97.0
996    95.0
997    90.0
998    92.0
999    84.0
Name: date, Length: 1000, dtype: float64

# time

In [59]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [60]:
# convert into datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [61]:
time['hours'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

In [62]:
time.head()

,date,msg,hours,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [63]:
# extract time
time['time'] = time['date'].dt.time
time.head()

,date,msg,hours,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [64]:
# time difference
today-time['date']

0     4664 days 11:58:04.836722
1     4528 days 13:08:04.836722
2     5014 days 12:27:04.836722
3     4316 days 12:17:04.836722
4     4713 days 13:37:04.836722
                 ...
995   5303 days 11:58:04.836722
996   4624 days 13:34:04.836722
997   5089 days 13:11:04.836722
998   5205 days 13:14:04.836722
999   4477 days 13:23:04.836722
Name: date, Length: 1000, dtype: timedelta64[ns]

In [66]:
(today - time['date']).dt.total_seconds()

0      4.030127e+08
1      3.912665e+08
2      4.332544e+08
3      3.729466e+08
4      4.072522e+08
           ...
995    4.582223e+08
996    3.995624e+08
997    4.397371e+08
998    4.497596e+08
999    3.868610e+08
Name: date, Length: 1000, dtype: float64

In [67]:
# in minutes
(today - time['date']).dt.total_seconds() / 60

0      6.716878e+06
1      6.521108e+06
2      7.220907e+06
3      6.215777e+06
4      6.787537e+06
           ...
995    7.637038e+06
996    6.659374e+06
997    7.328951e+06
998    7.495994e+06
999    6.447683e+06
Name: date, Length: 1000, dtype: float64

In [68]:
# in hours
(today - time['date']).dt.total_seconds() / 3600

0      111947.968010
1      108685.134677
2      120348.451344
3      103596.284677
4      113125.618010
           ...
995    127283.968010
996    110989.568010
997    122149.184677
998    124933.234677
999    107461.384677
Name: date, Length: 1000, dtype: float64