In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('covid_toy.csv')

In [4]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [7]:
df.isnull().sum()
# this will show 10 value in fever is null

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [8]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

# in x we drop has_covid col, and in y only has_covid is used

# without Column Transformer

In [11]:
# imputing missing value form fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
X_train_fever.shape

(80, 1)

In [13]:
# Ordinal Encoding for cough column
oe = OrdinalEncoder(categories=[['Mild','Strong']])

X_test_cough = oe.fit_transform(X_test[['cough']])
# also for test data
X_train_cough = oe.fit_transform(X_train[['cough']])
X_train_cough.shape

(80, 1)

In [15]:
# One Hot Encoding for Gender And City
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also for test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])
X_train_gender_city.shape

(80, 4)

In [16]:
# Extracting age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also for test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values
X_train_age.shape

(80, 1)

In [19]:
# merging
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)
X_train_transformed.shape

(80, 7)

# With column Transformer

In [20]:
from sklearn.compose import ColumnTransformer

In [21]:
tranformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
     ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
     ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [22]:
x_train_transformed = tranformer.fit_transform(X_train)
x_test_transformed = tranformer.fit_transform(X_test)

In [25]:
x_train_transformed.shape

(80, 7)

In [24]:
x_test_transformed.shape

(20, 7)